### ISSUE TITLE
error in pure windows environment

### ISSUE THREAD

**Issue by Kensuke-Mitsuzawa** [Kensuke-Mitsuzawa/sumo_docker_pipeline#10]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kensu\miniconda3\lib\site-packages\sumo_docker_pipeline\pipeline.py", line 77, in run_simulation
    sumo_result_obj = sumo_controller.start_job(target_scenario_name=self.scenario_name,
  File "C:\Users\kensu\miniconda3\lib\site-packages\sumo_docker_pipeline\docker_operation_module.py", line 155, in start_job
    command_message = self.client.containers.run(image=self.image_name,
  File "C:\Users\kensu\miniconda3\lib\site-packages\docker\models\containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "C:\Users\kensu\miniconda3\lib\site-packages\docker\models\containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "C:\Users\kensu\miniconda3\lib\site-packages\docker\api\container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "C:\Users\kensu\miniconda3\lib\site-packages\docker\api\container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "C:\Users\kensu\miniconda3\lib\site-packages\docker\api\client.py", line 274, in _result
    self._raise_for_status(response)
  File "C:\Users\kensu\miniconda3\lib\site-packages\docker\api\client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "C:\Users\kensu\miniconda3\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for https://192.168.99.101:2376/v1.40/containers/create?name=sumo-docker-test-scenario-1625340007.602809-1625347598.188606: Internal Server Error ("invalid volume specification: 'C:\Users\kensu\AppData\Local\Temp\tmpiat2uy4v:/mount_dir:rw'")
```

**Comment by Kensuke-Mitsuzawa** [comment]
Try in windows env

```
kensu@LAPTOP-E2S9C3LV MINGW64 ~/codes/eurecom
$ docker run -it -v C:\Users\kensu\codes\eurecom\test-sumo-docker-pipeline:/
mount_dir kensukemi/sumo-ubuntu18
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid mode: /mount_dir.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

kensu@LAPTOP-E2S9C3LV MINGW64 ~/codes/eurecom
$ docker run -it -v C:\Users\kensu\codes\eurecom\test-sumo-docker-pipeline:\
mount_dir kensukemi/sumo-ubuntu18
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid mode: mount_dir.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

kensu@LAPTOP-E2S9C3LV MINGW64 ~/codes/eurecom
$ docker run -it -v C:\Users\kensu\codes\eurecom\test-sumo-docker-pipeline:\
mount_dir:rw kensukemi/sumo-ubuntu18
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid volume specification: 'C:Userskensucodeseurecomtest-sumo-docker-pipeline:mount_dir:rw'.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

kensu@LAPTOP-E2S9C3LV MINGW64 ~/codes/eurecom
$ docker run -it -v /c/Users/kensu/codes/eurecom/test-sumo-docker-pipeline:/ mount_dir:rw kensukemi/sumo-ubuntu18
root@3921c5fdd12b:/# exit
exit
```

Result

- if Path is windows format -> fail
- if Path is Unix format -> pass

**Comment by Kensuke-Mitsuzawa** [comment]
pathlib can convert the path into Unix form

```
In [3]: a = pathlib.Path('./')

In [4]: a
Out[4]: WindowsPath('.')

In [5]: a.absolute()
Out[5]: WindowsPath('C:/Users/kensu')

In [6]: a.absolute().as_posix()
Out[6]: 'C:/Users/kensu'
```

But, this is not enough. `C:` should be `/c`
